stages:
  - prepare
  - prechecks
  - mpi
  - legion

variables:
  PROJECT_NAME: flecsi-sp
  GIT_SUBMODULE_STRATEGY: normal
  ENABLE_CDASH: false
  ENABLED_CLUSTERS: "darwin"

include:
 - .gitlab/common.yml

format:
  extends: [.ascgit_job, .darwin_job, .darwin_regular_job, .clang_format]
  stage: prechecks

check_warnings:
  allow_failure: true
  extends: [.ascgit_job, .darwin_job, .darwin_regular_job, .check_warnings]
  stage: prechecks

###############################################################################
# Darwin
###############################################################################

darwin_flecsi-sp-lib_test_mpi_gnu:
  stage: mpi
  extends: [.ascgit_job, .darwin_job, .darwin_regular_job, .build_and_test]
  needs: []
  variables:
    SPACK_ENV_NAME: "mpi/openmpi-gnu"

# darwin_flecsi-sp-lib_test_mpi_cuda:
#   stage: mpi
#   extends: [.ascgit_job, .darwin_job, .darwin_regular_job, .build_and_test]
#   needs: []
#   variables:
#     SPACK_ENV_NAME: "mpi/openmpi-cuda-clang"
#     SCHEDULER_PARAMETERS: "-N 1 --qos=debug -p shared-gpu-ampere"

darwin_flecsi-sp-lib_test_legion:
  stage: legion
  extends: [.ascgit_job, .darwin_job, .darwin_regular_job, .build_and_test]
  needs: []
  variables:
    SPACK_ENV_NAME: "legion/openmpi-gnu"
